// <auto-generated />
using LeiaJa.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeiaJa.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250129152659_CREATEMIGRATIONS")]
    partial class CREATEMIGRATIONS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeiaJa.Domain.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Categoria");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("TBL_CATEGORY", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Romântico",
                            Description = "msnmansmnamnsman"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Desenvolvimento Pessoal",
                            Description = "jakdjakjsakjakljkjasj"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Finanças",
                            Description = "dhsjkdjskd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
