global using Microsoft.EntityFrameworkCore;
global using LeiaJa.Domain.Entities;
global using LeiaJa.Domain.Interfaces;
global using LeiaJa.Domain.Pagination;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Linq.Expressions;
global using LeiaJa.Infrastructure.Context;
global using LeiaJa.Infrastructure.Helper;
global using Microsoft.Extensions.Logging;
