global using LeiaJa.Domain.Interfaces;
global using System.ComponentModel.DataAnnotations;
global using LeiaJa.Application.DTOs.Livro;
global using AutoMapper;
global using LeiaJa.Domain.Common;
global using LeiaJa.Domain.Entities;
global using LeiaJa.Domain.Pagination;
global using LeiaJa.Application.UseCase.Livro;
global using LeiaJa.Application.Interfaces;
